// Real size-spec generator. Builds a graded (XS–3XL) size chart from GRACE's
// existing fitBlocks size-guide engine and serializes it to CSV — wired behind
// the "Generate size chart" prepress fix and the assistant's "Create Size Spec".

import { getConsumerSizeGuide, fitLabel, formatInches } from '@/lib/fitBlocks/sizeGuide'
import { resolveGarmentType } from '@/lib/fitBlocks'
import { ALL_SIZES, type GarmentType, type SizeKey } from '@/lib/fitBlocks/types'

export interface SizeSpec {
  garmentType: GarmentType
  garmentLabel: string
  fitLabel: string
  sizes: readonly SizeKey[]
  rows: { label: string; hint: string; values: Record<SizeKey, number> }[]
}

const prettyGarment = (t: string) => t.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())

/** Build a graded size spec for a garment (defaults to a standard short-sleeve tee). */
export function buildSizeSpec(garmentHint?: string, fit?: string): SizeSpec | null {
  const gt = (garmentHint && resolveGarmentType(garmentHint)) || ('short_sleeve_tee' as GarmentType)
  const guide = getConsumerSizeGuide(gt, fit as never)
  if (!guide) return null
  return {
    garmentType: guide.garmentType,
    garmentLabel: prettyGarment(guide.garmentType),
    fitLabel: fitLabel(guide.fit),
    sizes: guide.sizes,
    rows: guide.rows.map(r => ({ label: r.label, hint: r.hint, values: r.values })),
  }
}

const csvCell = (s: string) => (/[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s)

export function sizeSpecToCsv(spec: SizeSpec): string {
  const header = ['Measurement (in)', ...spec.sizes].map(csvCell).join(',')
  const rows = spec.rows.map(r =>
    [csvCell(r.label), ...spec.sizes.map(s => formatInches(r.values[s] ?? 0))].join(','))
  const notes = `\n# ${spec.garmentLabel} · ${spec.fitLabel} fit · graded XS–3XL · generated by GRACE`
  return [header, ...rows].join('\n') + '\n' + notes
}

/** One-line, human summary for the assistant/report. */
export function sizeSpecSummary(spec: SizeSpec): string {
  const key = spec.rows.find(r => /chest|waist/i.test(r.label)) ?? spec.rows[0]
  const vals = spec.sizes.map(s => key?.values[s]).filter((v): v is number => typeof v === 'number')
  const range = vals.length ? `${formatInches(Math.min(...vals))}–${formatInches(Math.max(...vals))}"` : ''
  return `Generated a graded XS–3XL size spec for a ${spec.fitLabel.toLowerCase()} ${spec.garmentLabel}` +
    (key && range ? ` — ${key.label.toLowerCase()} runs ${range} across sizes.` : '.')
}

/** Client-side file download (assistant + report both call this). */
export function downloadTextFile(filename: string, content: string, mime = 'text/csv') {
  try {
    const blob = new Blob([content], { type: `${mime};charset=utf-8` })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  } catch { /* no-op outside the browser */ }
}
