import type { TopFitLibrary, TopFitBlock, GraphicPlacement, SupplierExportMapping, TopMeasurementSet } from '../../types'
import { buildTopSizeChart, TOP_FIT_TRANSFORMS } from '../../transformRules'
import { BENCHMARKS } from '../../benchmarks'

const b = BENCHMARKS.track_jacket

// Track jacket benchmark is Standard, not Relaxed.
// The transform table is relative to Relaxed, so the Standard base here IS the benchmark.
// Oversized/Relaxed are generated by ADDING ease from this standard base.

const standardBaseM: TopMeasurementSet = {
  consumer: {
    chest:         b.publishedMeasurementsAtM.chest,        // 20
    frontLength:   b.publishedMeasurementsAtM.frontLength,  // 28
    shoulderWidth: 18.0,  // standard fit, narrower set
    sleeveLength:  b.publishedMeasurementsAtM.sleeveLength, // 25.5
  },
  technical: {
    armhole:       9.75,  // higher armhole for athletic range of motion
    bottomOpening: 20.0,
    neckOpening:   7.75,
    sleeveOpening: 5.5,
    cuffLength:    2.0,
    cuffOpening:   5.5,
    backLength:    28.5,
  },
}

// For track jacket, the benchmark IS Standard.
// "Relaxed" = standard + ease offsets (reverse of tee logic where relaxed is the benchmark).
// We re-use the same transform table but invert the direction for variants relative to standard.
function buildFromStandard(chestOffset: number, shoulderOffset: number, frontLengthOffset = 0): TopMeasurementSet {
  return {
    consumer: {
      chest:         standardBaseM.consumer.chest         + chestOffset,
      frontLength:   standardBaseM.consumer.frontLength   + frontLengthOffset,
      shoulderWidth: standardBaseM.consumer.shoulderWidth + shoulderOffset,
      sleeveLength:  standardBaseM.consumer.sleeveLength,
    },
    technical: {
      armhole:        standardBaseM.technical.armhole        + chestOffset * 0.25,
      bottomOpening:  standardBaseM.technical.bottomOpening  + chestOffset,
      neckOpening:    standardBaseM.technical.neckOpening,
      sleeveOpening:  standardBaseM.technical.sleeveOpening,
      cuffLength:     standardBaseM.technical.cuffLength,
      cuffOpening:    standardBaseM.technical.cuffOpening,
      backLength:     standardBaseM.technical.backLength!     + frontLengthOffset,
    },
  }
}

const PLACEMENTS: GraphicPlacement[] = [
  { location: 'left_chest',  xOffsetInches: -4.5, yOffsetInches: 4.5, maxWidthInches: 3.5, maxHeightInches: 3.5, widthGradePerSize: 0, notes: 'Primary: left chest logo. Center chest typically split by zip.' },
  { location: 'upper_back',  xOffsetInches: 0, yOffsetInches: 4.5, maxWidthInches: 13, maxHeightInches: 5, widthGradePerSize: 0.5, notes: 'Back yoke print.' },
  { location: 'center_back', xOffsetInches: 0, yOffsetInches: 9.0, maxWidthInches: 13, maxHeightInches: 11, widthGradePerSize: 0.5, notes: 'Large back graphic.' },
  { location: 'left_sleeve', xOffsetInches: 0, yOffsetInches: 5.0, maxWidthInches: 3, maxHeightInches: 8, widthGradePerSize: 0, notes: 'Sleeve stripe or text.' },
]

const EXPORT_MAPPINGS: SupplierExportMapping[] = [
  { field: 'consumer.chest',         supplierLabel: 'Chest (1/2)',          exportVisible: true, displayMultiplier: 1, unit: 'in', notes: 'Measured flat with zip closed' },
  { field: 'consumer.frontLength',   supplierLabel: 'Front Length (HPS)',   exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'consumer.shoulderWidth', supplierLabel: 'Shoulder Width',       exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'consumer.sleeveLength',  supplierLabel: 'Sleeve Length',        exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'technical.armhole',      supplierLabel: 'Armhole (straight)',   exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'technical.bottomOpening',supplierLabel: 'Bottom Opening (1/2)', exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'technical.neckOpening',  supplierLabel: 'Neck Opening',         exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'technical.cuffOpening',  supplierLabel: 'Cuff Opening (1/2)',   exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'technical.cuffLength',   supplierLabel: 'Cuff Length',          exportVisible: true, displayMultiplier: 1, unit: 'in' },
  { field: 'technical.backLength',   supplierLabel: 'Back Length (HPS)',    exportVisible: true, displayMultiplier: 1, unit: 'in' },
]

const FITS: Partial<Record<TopFitBlock['fitVariant'], TopMeasurementSet>> = {
  standard:          standardBaseM,
  relaxed:           buildFromStandard(1.0, 0.5),
  oversized:         buildFromStandard(3.0, 1.5, 1.0),
  vintage_oversized: buildFromStandard(4.0, 2.0, -0.5),
  cropped:           buildFromStandard(0, 0, -3.5),
}

const RULES: Partial<Record<TopFitBlock['fitVariant'], string[]>> = {
  relaxed:           ['Relaxed adds +1" chest, +0.5" shoulder from Standard benchmark.'],
  oversized:         ['Oversized adds +3" chest, +1.5" shoulder, +1" length from Standard.'],
  vintage_oversized: ['Vintage Oversized adds +4" chest, +2" shoulder; body shortens -0.5" vs Oversized for boxy proportion.'],
  cropped:           ['Cropped maintains Standard width; body length -3.5".'],
}

export const trackJacket: TopFitLibrary = {
  garmentType:   'track_jacket',
  defaultFit:    'standard',
  availableFits: ['standard', 'relaxed', 'oversized', 'vintage_oversized', 'cropped'],
  fits: Object.fromEntries(
    (Object.entries(FITS) as [TopFitBlock['fitVariant'], TopMeasurementSet][]).map(([variant, baseM]) => [
      variant,
      {
        garmentType:  'track_jacket' as const,
        fitVariant:   variant,
        isBenchmark:  variant === 'standard',
        benchmark:    variant === 'standard' ? b.source : undefined,
        transformationRules: variant === 'standard' ? undefined : RULES[variant],
        sizeChart:    buildTopSizeChart(baseM),
        graphicPlacements: PLACEMENTS,
        supplierExportMappings: EXPORT_MAPPINGS,
        internalNotes: variant === 'standard'
          ? [`Benchmark: ${b.source.brand} ${b.source.productName} (${b.source.sku}).`]
          : (RULES[variant] ?? []),
      } satisfies TopFitBlock,
    ])
  ) as TopFitLibrary['fits'],
}
